#!/bin/bash
#PBS -jeo
#PBS -r n
#PBS -l nodes=1:ppn=16
#PBS -l walltime=24:00:00

module load MPI/impi/2017.0.4; module load MKL/2017.4.239; module load Compiler/GCC/5.3.1;

export RUN_DIR=${HOME}/vasp/$PBS_JOBNAME
cd ${RUN_DIR}

echo $PBS_JOBNAME
hostname
echo "PBS_NP = " ${PBS_NP}
echo "TMPDIR = " ${TMPDIR}
date
echo ""

if [ -e "INCAR" ]; then
 mpirun -np ${PBS_NP} /home/a.zhugayevych/bin/vasp/vasp_std
else
 n=$(\ls INCAR* -afq | wc -l)
 echo "number of INCARs = " $n
 for ((i=1; i <= $n; i++))
 do
  if [ -e "INCAR"$i ]; then
    echo ""
    echo "INCAR"$i " exists"
    cp INCAR$i INCAR
    mpirun -np ${PBS_NP} /home/a.zhugayevych/bin/vasp/vasp_std
    cp OUTCAR OUTCAR$i
    rm INCAR OUTCAR
    echo ""
  else
    echo "Wrong format of INCAR* files. Use INCAR1, INCAR2,..."
  fi
 done
fi

echo ""
date

echo "done"
