#!/bin/bash

jobname=
ncores=16
nnodes=1
walltime=336:00:00
queue=AMG
prog=M

while getopts :J:n:N:t:p:P: opt; do
 case $opt in
  J) jobname=$OPTARG;;
  n) ncores=$OPTARG;;
  N) nnodes=$OPTARG;;
  t) walltime=$OPTARG;;
  p) queue=$OPTARG;;
  P) prog=$OPTARG;;
  ?) echo "Invalid option: -$OPTARG"
     echo "Usage: _pbs [-J jobname] [-n ncores] [-N nnodes] [-t walltime] [-p queue] [-P prog]"
     exit;;
 esac
done

echo "jobname=$jobname, ncores=$ncores, nnodes=$nnodes, walltime=$walltime, queue=$queue, prog=$prog"

if [ "$jobname" == "" ];  then echo "Invalid jobname: provide nonempty job name"; exit; fi
if [ "$nnodes" -ne "1" ]; then echo "Invalid nnodes: only 1 node can be requested"; exit; fi
if [ "$queue" != "AMG" ]; then echo "Invalid queue: only AMG queue is available"; exit; fi


module add prun/1.0
module add intel/16.0.2.181
module add impi/5.1.3.181

#rm -rf /scratch/vasp/$1
#cp -r ~/vasp/$1 ~/_scratch/vasp/
#cd ~/_scratch/vasp/$1/

#sbatch -J $jobname -n $ncores -N $nnodes -t $walltime -p $queue /opt/vasp/vasp5.4.1MPI #--exclude=node-amg03
case $prog in
 M) sbatch -J $jobname -n $ncores -N $nnodes -t $walltime -p $queue /opt/vasp/vasp5.4.1MPI;;
 G) sbatch -J $jobname -n $ncores -N $nnodes -t $walltime -p $queue /opt/vasp/vasp5.4.1MPI_gam;;
 N) sbatch -J $jobname -n $ncores -N $nnodes -t $walltime -p $queue /opt/vasp/vasp5.4.1MPI_ncl;;
 *) echo "Invalid prog=$prog, can be one of [M,G,N]"
    exit;;
esac

#sbatch -J $1 -p $2 -t $3:0:0 --ntasks-per-node $4 -N $5 ~/ompi_script_vasp --mca btl openib,sm,self /opt/VASP/bin/vasp.5.3.openmpi-1.5.5
#sbatch -p $2 -J $1 -t 0:15:0 --ntasks-per-node $2 -N $3 ~/ompi_script_vasp --mca btl openib,sm,self /opt/VASP/bin/vasp.5.3.openmpi-1.5.5
#cd ~/
