#!/bin/bash
#PBS -jeo
#PBS -r n
#PBS -l nodes=1:ppn=16
#PBS -l walltime=72:00:00

module load PBS/tools Compilers/Intel/psxe_2015.6  QCh/VASP/5.4.1p1/psxe2015.6

numcores=$(echo "$PBS_NUM_NODES * $PBS_NUM_PPN" | bc -l)
export OMP_NUM_THREADS=1

export RUN_DIR=~/vasp/$PBS_JOBNAME
rm -rf $TMPDIR/${RUN_DIR}
cp -r ${RUN_DIR} $TMPDIR/
cd $TMPDIR/$PBS_JOBNAME

echo $PBS_JOBNAME
hostname
pwd
echo "pbs_num_procs =" $numcores
date
echo ""


# ---- new code block ----
if [ -e "INCAR" ]; then
 mpiexec.hydra -np $numcores $VASP/bin/vasp_std
else
 n=$(\ls INCAR* -afq | wc -l)
 echo "number of INCARs =" $n
 for ((i=1; i <= $n; i++))
 do
  if [ -e "INCAR"$i ]; then
    echo ""
    echo "INCAR"$i " exists"
    cp -f INCAR$i INCAR
    mpiexec.hydra -np $numcores $VASP/bin/vasp_std
    cp OUTCAR OUTCAR$i
    rm INCAR OUTCAR
    echo ""
  else
    echo "Wrong format of INCAR* files. Use INCAR1, INCAR2,..."
  fi
 done
fi
# ---- end of new code block ----

echo ""
date

cp $TMPDIR/$PBS_JOBNAME/* ${RUN_DIR}/
rm -rf $TMPDIR/${RUN_DIR}
cd

echo "done"
