#!/bin/bash

#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 24:00:00
#SBATCH -o %x.e%j
#SBATCH -e %x.e%j.err
#SBATCH -p AMG
#SBATCH --mem-per-cpu=7675

#export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export OMP_NUM_THREADS=16

echo 'JOBNAME' $SLURM_JOB_NAME
echo 'NUM_THREADS' $OMP_NUM_THREADS
hostname
date

ulimit -u unlimited
module load Compiler/Intel/17u8  Q-Ch/VASP/5.4.4_OPT

cd ~/vasp/$SLURM_JOB_NAME

mpirun -n 16 vasp_std

date
rm -f ~/$SLURM_JOB_NAME.e$SLURM_JOB_ID.err
