#!/bin/bash

#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 24:00:00
#SBATCH -o %x.e%j
#SBATCH -e %x.e%j.err
#SBATCH -p AMG
#SBATCH --mem-per-cpu=7675

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

echo 'JOBNAME' $SLURM_JOB_NAME
echo 'NUM_THREADS' $OMP_NUM_THREADS
hostname
date

module load Compiler/Intel/17u8 Q-Ch/ABINIT/8.10.3/intel/2017u8

cd ~/abinit

mpirun abinit < $SLURM_JOB_NAME.files > $SLURM_JOB_NAME.log

date
rm -f ~/$SLURM_JOB_NAME.e$SLURM_JOB_ID.err
