#!/bin/bash
#PBS -j eo
#PBS -r n
#PBS -l nodes=1:ppn=8
####PBS -V
hostname
date

module load  Compiler/Intel/psxe_2019.5  MPI/impi/2019.5.281

cd ~/abinit

mpirun ~/local/abinit/abinit < $PBS_JOBNAME.files > $PBS_JOBNAME.log > $PBS_JOBNAME.err

date
#rm -f ~/abinit/$PBS_JOBNAME.err
