#!/bin/bash

#SBATCH -N 1
#SBATCH -c 16
#SBATCH -t 24:00:00
#SBATCH -o %x.e%j
#SBATCH -e %x.e%j.err
#SBATCH -p AMG
#SBATCH --mem-per-cpu=7675

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

echo 'JOBNAME' $SLURM_JOB_NAME
echo 'NUM_THREADS' $OMP_NUM_THREADS
hostname
date

export g16root=/opt/cms/q-ch/gaussian/A03/
source $g16root/g16/bsd/g16.profile

export GAUSS_SCRDIR=/scr2/amg/$SLURM_JOB_NAME.$SLURM_JOB_ID
mkdir -p $GAUSS_SCRDIR
echo 'GAUSS_SCRDIR' $GAUSS_SCRDIR
cd ~/gaussian

g16 < $SLURM_JOB_NAME.gau > $SLURM_JOB_NAME.out

rm -rf $GAUSS_SCRDIR
date
rm -f ~/$SLURM_JOB_NAME.e$SLURM_JOB_ID.err
