#!/bin/bash
#SBATCH -o %x.e%j
#SBATCH -e %x.e%j.err
#SBATCH -N 1        ## --nodes=
#SBATCH -c 20       ## --cpus-per-task=
#SBATCH -t 36:00:00
#SBATCH --ntasks-per-node=1
#SBATCH -p CPU_Std20

ulimit -s unlimited
ulimit -t unlimited

echo 'JOB_NAME' $SLURM_JOB_NAME
echo 'JOB_ID' $SLURM_JOB_ID
echo 'JOB_CPUS_PER_NODE' $SLURM_JOB_CPUS_PER_NODE
hostname
date

#module load gaussian/g16
export g16root=/sw/linux/gaussian/g16
. $g16root/g16/bsd/g16.profile

export GAUSS_PDEF=${SLURM_CPUS_PER_TASK}
export GAUSS_SCRDIR=/usr/scratch/$SLURM_JOB_USER/$SLURM_JOB_ID
echo 'GAUSS_PDEF' $GAUSS_PDEF
echo 'GAUSS_SCRDIR' $GAUSS_SCRDIR

mkdir -p $GAUSS_SCRDIR
rsync -a pckr232:~/gaussian/$SLURM_JOB_NAME.* $GAUSS_SCRDIR
rsync -a pckr232:~/bin/readdump $GAUSS_SCRDIR
cd $GAUSS_SCRDIR

g16 < $SLURM_JOB_NAME.gau >> $SLURM_JOB_NAME.out

./readdump $SLURM_JOB_NAME.rwf $SLURM_JOB_NAME.637 637
./readdump $SLURM_JOB_NAME.rwf $SLURM_JOB_NAME.s1e s1e

rsync -a $GAUSS_SCRDIR/$SLURM_JOB_NAME.out ~/gaussian
rsync -a $GAUSS_SCRDIR/$SLURM_JOB_NAME.637 ~/gaussian
rsync -a $GAUSS_SCRDIR/$SLURM_JOB_NAME.s1e ~/gaussian
rm -rf $GAUSS_SCRDIR
date
if [[ ! -s ~/$SLURM_JOB_NAME.e$SLURM_JOB_ID.err ]]; then rm -f ~/$SLURM_JOB_NAME.e$SLURM_JOB_ID.err; fi
