#!/bin/bash

jobname=
ncores=1
nnodes=1
walltime=24:00:00
queue=AMG

while getopts :J:n:N:t:p: opt; do
 case $opt in
  J) jobname=$OPTARG;;
  n) ncores=$OPTARG;;
  N) nnodes=$OPTARG;;
  t) walltime=$OPTARG;;
  p) queue=$OPTARG;;
  ?) echo "Invalid option: -$OPTARG"
     echo "Usage: _pbs [-J jobname] [-n ncores] [-N nnodes] [-t walltime] [-p queue]"
     exit;;
 esac
done

echo "jobname=$jobname, ncores=$ncores, nnodes=$nnodes, walltime=$walltime, queue=$queue"

if [ "$jobname" == "" ];  then echo "Invalid jobname: provide nonempty job name"; exit; fi
if [ "$nnodes" -ne "1" ]; then echo "Invalid nnodes: only 1 node can be requested"; exit; fi
if [ "$queue" != "AMG" ]; then echo "Invalid queue: only AMG queue is available"; exit; fi

sbatch -J $jobname -c $ncores -N $nnodes -t $walltime -p $queue /opt/gaussian/gaussian
