#!/bin/bash
#PBS -j eo
#PBS -r n
#PBS -l nodes=1:ppn=1
hostname
date

export g09root=/home/Andriy.Zhugayevych/local/gaussian
source $g09root/g09/bsd/g09.profile

export RUN_DIR=~/gaussian/
export GAUSS_SCRDIR=$TMPDIR/$PBS_JOBNAME

rm -rf $GAUSS_SCRDIR
mkdir -p $GAUSS_SCRDIR
cd ${RUN_DIR}

g09 < $PBS_JOBNAME.gau > $PBS_JOBNAME.out

rm -rf $GAUSS_SCRDIR
date
