#!/bin/bash
#SBATCH -o %x.e%j
#SBATCH -e %x.e%j.err
#SBATCH -N 1        ## --nodes=
#SBATCH -c 16       ## --cpus-per-task=
#SBATCH -t 24:00:00
#SBATCH -p AMG
#SBATCH --ntasks-per-node=1
#SBATCH --mem=0

echo 'JOB_NAME' $SLURM_JOB_NAME
echo 'JOB_ID' $SLURM_JOB_ID
echo 'JOB_CPUS_PER_NODE' $SLURM_JOB_CPUS_PER_NODE
hostname
date

module load Q-Ch/Gaussian/16.RevA03

export GAUSS_SCRDIR=/scr/$SLURM_JOB_USER/$SLURM_JOB_ID
echo 'GAUSS_SCRDIR' $GAUSS_SCRDIR

cd ~/gaussian

g16 < $SLURM_JOB_NAME.gau > $SLURM_JOB_NAME.out

date
rm -f ~/$SLURM_JOB_NAME.e$SLURM_JOB_ID.err
